# -*- coding: utf-8 -*-
"""Predictedyou.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O-TJ8r_vJWmCPPOavXGA_zUhEy3sprAY
"""

# =====================================================
# STREAMLIT APP: PREDICTED YOU vs REAL YOU
# =====================================================

# Install necessary libraries
#!pip install -q streamlit sentence-transformers joblib

import streamlit as st
import numpy as np
import joblib
from sentence_transformers import SentenceTransformer
import os

# =====================================================
# Load models (CACHED)
# =====================================================

@st.cache_resource
def load_models():
    embedder_path = "sentence_embedder.pkl"
    embedder = None
    try:
        # Try to load the local pickled SentenceTransformer model
        embedder = joblib.load(embedder_path)
        st.success("Sentence embedder loaded successfully from local file.")
    except (EOFError, FileNotFoundError, joblib.externals.loky.process_executor.BrokenProcessPool) as e:
        st.warning(f"Could not load sentence embedder from '{embedder_path}': {e}")
        st.info("Attempting to download and save a default SentenceTransformer model.")
        try:
            # If loading fails, download a default model and save it
            default_model_name = "all-MiniLM-L6-v2"
            embedder = SentenceTransformer(default_model_name)
            joblib.dump(embedder, embedder_path)
            st.success(f"Downloaded and saved '{default_model_name}' as '{embedder_path}'.")
        except Exception as download_e:
            st.error(f"Failed to download and save default SentenceTransformer model: {download_e}")
            raise

    models = {
        "Extraversion": joblib.load("E_label_classifier.pkl"),
        "Openness": joblib.load("J_label_classifier.pkl"),
        "Conscientiousness": joblib.load("N_label_classifier.pkl"),
        "Agreeableness": joblib.load("T_label_classifier.pkl"),
    }
    return embedder, models

embedder, models = load_models()

# =====================================================
# Core inference (pure ML)
# =====================================================

def predict_personality(text: str) -> dict:
    embedding = embedder.encode([text])

    predictions = {}
    probabilities = {}

    for trait, model in models.items():
        pred = model.predict(embedding)[0]
        prob = model.predict_proba(embedding)[0][pred]

        predictions[trait] = "High" if pred == 1 else "Low"
        probabilities[trait] = round(float(prob), 3)

    return {
        "prediction": predictions,
        "confidence": probabilities
    }

# =====================================================
# Question bank
# =====================================================

QUESTION_BANK = {
    "Extraversion": [
        "Do you feel energized when spending time with groups of people?",
        "How do you usually behave in social gatherings?"
    ],
    "Openness": [
        "Do you enjoy exploring new ideas or philosophies?",
        "How do you react to unconventional opinions?"
    ],
    "Conscientiousness": [
        "How do you plan and organize your daily tasks?",
        "What is your approach to deadlines?"
    ],
    "Agreeableness": [
        "How do you usually handle conflicts with others?",
        "How important is empathy in your relationships?"
    ]
}

# =====================================================
# Streamlit UI
# =================================0====================

st.set_page_config(page_title="Predicted You vs Real You", layout="centered")
st.title("🧠 Predicted You vs Real You")

mode = st.radio(
    "Choose Mode",
    ["Predicted You (Essay)", "Real You (Interactive)", "Comparison"]
)

# =====================================================
# PREDICTED YOU
# =====================================================

if mode == "Predicted You (Essay)":
    st.header("✍️ Predicted You")

    essay = st.text_area(
        "Write about yourself (essay / bio / thoughts)",
        height=250
    )

    if st.button("Analyze"):
        if len(essay.strip()) < 100:
            st.warning("Please write at least 100 characters.")
        else:
            result = predict_personality(essay)
            st.session_state["predicted_you"] = result

            st.subheader("Result")
            for trait in result["prediction"]:
                st.write(
                    f"**{trait}**: {result['prediction'][trait]} "
                    f"(confidence: {result['confidence'][trait]})"
                )

# =====================================================
# REAL YOU
# =====================================================

elif mode == "Real You (Interactive)":
    st.header("💬 Real You Chatbot")

    if "real_text" not in st.session_state:
        st.session_state.real_text = ""
        st.session_state.q_index = 0
        st.session_state.questions = [
            q for qs in QUESTION_BANK.values() for q in qs
        ]

    if st.session_state.q_index < len(st.session_state.questions):
        question = st.session_state.questions[st.session_state.q_index]
        st.write(f"❓ {question}")

        answer = st.text_input(
            "Your answer",
            key=f"answer_{st.session_state.q_index}"
        )

        if st.button("Next"):
            st.session_state.real_text += " " + answer
            st.session_state.q_index += 1
            st.experimental_rerun()
    else:
        st.success("Enough data collected!")

        result = predict_personality(st.session_state.real_text)
        st.session_state["real_you"] = result

        st.subheader("Real You Profile")
        for trait in result["prediction"]:
            st.write(
                f"**{trait}**: {result['prediction'][trait]} "
                f"(confidence: {result['confidence'][trait]})"
            )

# =====================================================
# COMPARISON
# =====================================================

elif mode == "Comparison":
    st.header("⚖️ Comparison")

    if "predicted_you" not in st.session_state or "real_you" not in st.session_state:
        st.warning("Please complete both Predicted You and Real You first.")
    else:
        p = st.session_state["predicted_you"]
        r = st.session_state["real_you"]

        for trait in p["prediction"]:
            st.markdown(f"### {trait}")
            st.write(
                f"Predicted You: {p['prediction'][trait]} "
                f"(conf: {r['confidence'][trait]})"
            )
            st.write(
                f"Real You: {r['prediction'][trait]} "
                f"(conf: {r['confidence'][trait]})"
            )