# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBmM-daye-HDni2NV-nMsnBMRDyVgraQ
"""

# =====================================================
# STREAMLIT FRONTEND: Predicted You vs Real You
# =====================================================

import streamlit as st
import requests

API_URL = "http://localhost:8000/predict"
# later we will change this to your deployed FastAPI URL

# =====================================================
# Question Bank
# =====================================================

QUESTION_BANK = {
    "Extraversion": [
        "Do you feel energized when spending time with groups of people?",
        "How do you usually behave in social gatherings?"
    ],
    "Openness": [
        "Do you enjoy exploring new ideas or philosophies?",
        "How do you react to unconventional opinions?"
    ],
    "Conscientiousness": [
        "How do you plan and organize your daily tasks?",
        "What is your approach to deadlines?"
    ],
    "Agreeableness": [
        "How do you usually handle conflicts with others?",
        "How important is empathy in your relationships?"
    ]
}

# =====================================================
# Helper
# =====================================================

def call_api(text):
    response = requests.post(API_URL, json={"text": text})
    return response.json()

# =====================================================
# UI
# =====================================================

st.set_page_config("Predicted You vs Real You", layout="centered")
st.title("🧠 Predicted You vs Real You")

mode = st.radio(
    "Choose Mode",
    ["Predicted You (Essay)", "Real You (Interactive)", "Comparison"]
)

# =====================================================
# Predicted You
# =====================================================

if mode == "Predicted You (Essay)":
    essay = st.text_area("Write about yourself", height=250)

    if st.button("Analyze"):
        if len(essay.strip()) < 100:
            st.warning("Please write at least 100 characters.")
        else:
            result = call_api(essay)
            st.session_state["predicted_you"] = result

            for trait in result["prediction"]:
                st.write(
                    f"**{trait}**: {result['prediction'][trait]} "
                    f"(confidence: {result['confidence'][trait]})"
                )

# =====================================================
# Real You
# =====================================================

elif mode == "Real You (Interactive)":

    if "real_text" not in st.session_state:
        st.session_state.real_text = ""
        st.session_state.q_index = 0
        st.session_state.questions = [
            q for qs in QUESTION_BANK.values() for q in qs
        ]

    if st.session_state.q_index < len(st.session_state.questions):
        q = st.session_state.questions[st.session_state.q_index]
        st.write(f"❓ {q}")
        answer = st.text_input("Your answer")

        if st.button("Next"):
            st.session_state.real_text += " " + answer
            st.session_state.q_index += 1
            st.experimental_rerun()
    else:
        result = call_api(st.session_state.real_text)
        st.session_state["real_you"] = result

        for trait in result["prediction"]:
            st.write(
                f"**{trait}**: {result['prediction'][trait]} "
                f"(confidence: {result['confidence'][trait]})"
            )

# =====================================================
# Comparison
# =====================================================

elif mode == "Comparison":

    if "predicted_you" not in st.session_state or "real_you" not in st.session_state:
        st.warning("Please complete both modes first.")
    else:
        p = st.session_state["predicted_you"]
        r = st.session_state["real_you"]

        for trait in p["prediction"]:
            st.markdown(f"### {trait}")
            st.write(f"Predicted: {p['prediction'][trait]} (conf: {p['confidence'][trait]})")
            st.write(f"Real: {r['prediction'][trait]} (conf: {r['confidence'][trait]})")